//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace server_components_data_access.Dataflow
{
    using System;
    using System.Collections.Generic;
    
    public partial class agent
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string AgentTypeCode { get; set; }
        public string URL { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Directory { get; set; }
        public string FilePattern { get; set; }
        public Nullable<int> DataMapID { get; set; }
        public string QueueLocation { get; set; }
        public string Custom { get; set; }
        public bool Enabled { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> LastExecuted { get; set; }
    }
}
