//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace server_components_data_access.Dataflow
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataFlowContext : DbContext
    {
        public DataFlowContext()
            : base("name=DataFlowContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<agent> agents { get; set; }
        public virtual DbSet<agent_schedule> agent_schedule { get; set; }
        public virtual DbSet<configuration> configurations { get; set; }
        public virtual DbSet<datamap> datamaps { get; set; }
        public virtual DbSet<datamap_agent> datamap_agent { get; set; }
        public virtual DbSet<entity> entities { get; set; }
        public virtual DbSet<file> files { get; set; }
        public virtual DbSet<lookup> lookups { get; set; }
        public virtual DbSet<statistic> statistics { get; set; }
        public virtual DbSet<log_application> log_application { get; set; }
        public virtual DbSet<log_ingestion> log_ingestion { get; set; }
    }
}
