//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace server_components_data_access.Dataflow
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_ingestion
    {
        public int ID { get; set; }
        public Nullable<System.Guid> EducationOrganizationId { get; set; }
        public string Level { get; set; }
        public string Operation { get; set; }
        public Nullable<int> AgentID { get; set; }
        public string Process { get; set; }
        public string Filename { get; set; }
        public string Result { get; set; }
        public string Message { get; set; }
        public Nullable<int> RecordCount { get; set; }
        public System.DateTime Date { get; set; }
    }
}
