//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace server_components_data_access.Dataflow
{
    using System;
    using System.Collections.Generic;
    
    public partial class statistic
    {
        public int ID { get; set; }
        public System.Guid EntityID { get; set; }
        public string EntityType { get; set; }
        public Nullable<int> TermDescriptorId { get; set; }
        public Nullable<short> SchoolYear { get; set; }
        public string Measure { get; set; }
        public Nullable<int> ValueInt { get; set; }
        public Nullable<decimal> ValueDecimal { get; set; }
        public string ValueVarchar { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
