// <auto-generated />
namespace DataFlow.Common.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AgentTableRename : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AgentTableRename));
        
        string IMigrationMetadata.Id
        {
            get { return "201712210736125_AgentTableRename"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
