//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace server_components_data_access.Dataflow
{
    using System;
    using System.Collections.Generic;
    
    public partial class datamap_agent
    {
        public int ID { get; set; }
        public int DataMapID { get; set; }
        public int AgentID { get; set; }
        public int ProcessingOrder { get; set; }
    
        public virtual agent agent { get; set; }
        public virtual datamap datamap { get; set; }
    }
}
