//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace server_components_data_access.Dataflow
{
    using System;
    using System.Collections.Generic;
    
    public partial class file
    {
        public int ID { get; set; }
        public string Filename { get; set; }
        public string URL { get; set; }
        public int AgentID { get; set; }
        public string Status { get; set; }
        public string Message { get; set; }
        public Nullable<int> Rows { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual agent agent { get; set; }
        public virtual file_status file_status { get; set; }
    }
}
